export enum EnumCategories {
    OFFICE_PRODUCTS = 'Office Products',
    TOYS = 'Toys & Games',
    KITCHEN_DINING = 'Kitchen & Dining',
    MUSICAL_INSTRUMENTS = 'Musical Instruments',
    BEAUTY = 'Beauty & Personal Care',
    HEALTH = 'Health & Household',
    SPORT = 'Sports & Outdoors',
    PET = 'Pet Supplies',
    CLOTHING = 'Clothing, Shoes & Jewelry',
    TOOLS = 'Tools & Home Improvement',
    GROCERY = ' Grocery & Gourmet Food',
    PATIO = 'Patio, Lawn & Garden',
    ART = 'Arts, Crafts & Sewing',
    BABY = 'Baby',
    BOOKS = 'Books',
    VIDEO_GAMES = 'Video Games',
    CAMERA = 'Camera & Photo Products',
    CONSUMER_ELECTRONIC = 'Consumer Electronics',
    ELECTRONIC = 'Electronics',
    HOME_KITCHEN = 'Home & Kitchen',
    AUTOMOTIVE = 'Automotive',
    INDUSTRIAL = 'Industrial & Scientific',
    CELL_PHONES = 'Cell Phones & Accessories',
    COMPUTERS = 'Computers & Accessories',
}
