export const categories = [
    // "https://www.katom.com/cat/utility-carts.html",
    'https://www.katom.com/cat/shelving-transport.html',
    'https://www.katom.com/cat/clearance-sale.html',
    'https://www.katom.com/cat/janitorial.html',
    'https://www.katom.com/cat/tabletop.html',
    'https://www.katom.com/cat/kitchen-supplies.html',
    'https://www.katom.com/cat/bakery-supplies.html',
    'https://www.katom.com/cat/bar-supplies.html',
    'https://www.katom.com/cat/pizza-equipment.html',
    'https://www.katom.com/cat/deli-equipment-supplies.html',
    'https://www.katom.com/cat/residential.html',
    'https://www.katom.com/cat/hotel-supplies.html',
    'https://www.katom.com/cat/coffee-supplies.html',
    'https://www.katom.com/cat/food-delivery.html',
    'https://www.katom.com/cat/break-room-equipment.html',
    'https://www.katom.com/cat/food-truck-equipment.html',
    'https://www.katom.com/cat/mexican-restaurant-supplies.html',
    'https://www.katom.com/cat/disposables-consumables.html',
]
