
function categories() {
    return [
        // 'https://www.rshughes.com/c/Face-Coverings-Masks/19001/',
        // 'https://www.rshughes.com/c/Facility-Cleaning-Solutions/19004/',
        // 'https://www.rshughes.com/c/Facility-Repurposing-For-COVID-19/19007/',
        // 'https://www.rshughes.com/c/Hand-Hygiene/19003/',
        // 'https://www.rshughes.com/l/Safety-Plus-COVID-19-Screening.html',
        // 'https://www.rshughes.com/c/Healthcare-Personnel-PPE/19006/',
        // 'https://www.rshughes.com/c/PPE-Organization/19009/',
        // 'https://www.rshughes.com/c/Social-Distancing-Signs-And-Supplies/19002/',
        // 'https://www.rshughes.com/c/Staff-And-Visitor-Screening-Equipment/19005/',
        // "https://www.rshughes.com/c/Downdraft-Sanding-Tables/1218704/",
        // "https://www.rshughes.com/c/Abrasive-Brush-Accessories/1096/",
        // "https://www.rshughes.com/c/Abrasive-Brush-Sets/1097/",
        // "https://www.rshughes.com/c/Bristle-Discs/1104/",
        // "https://www.rshughes.com/c/Cup-Brushes/1110/",
        // "https://www.rshughes.com/c/Hand-Wire-Brushes/1121/",
        // "https://www.rshughes.com/c/Radial-Bristle-Brushes/1125/",
        // "https://www.rshughes.com/c/Tube-Brushes/1133/",
        // "https://www.rshughes.com/c/Wheel-Brushes/1134/",
        // "https://www.rshughes.com/c/Abrasive-Hand-Files/1101/",
        // "https://www.rshughes.com/c/Sharpening-Stones/1131/",
        // "https://www.rshughes.com/c/Abrasive-Cones-Plugs/1099/",
        // "https://www.rshughes.com/c/Abrasive-Mounted-Points/1102/",
        // "https://www.rshughes.com/c/Buffing-Polishing-Accessories/1105/",
        // "https://www.rshughes.com/c/Buffing-Polishing-Compounds/1106/",
        // "https://www.rshughes.com/c/Buffing-Wheels/1107/",
        // "https://www.rshughes.com/c/Polishing-Discs-Pads/1123/",
        // "https://www.rshughes.com/c/Polishing-Rolls/1124/",
        // "https://www.rshughes.com/c/Cartridge-Rolls/1108/",
        // "https://www.rshughes.com/c/Cross-Square-Pads/1109/",
        // "https://www.rshughes.com/c/Flap-Wheel-Accessories/1145/",
        // "https://www.rshughes.com/c/Flap-Wheel-Mandrels/1146/",
        // "https://www.rshughes.com/c/Flap-Wheel-Sets/1147/",
        // "https://www.rshughes.com/c/Flap-Wheels-Flap-Brushes/1148/",
        // "https://www.rshughes.com/c/Sanding-Belts/1126/",
        // "https://www.rshughes.com/c/Hand-Pad-Accessories/1149/",
        // "https://www.rshughes.com/c/Hand-Pad-Sets/1151/",
        // "https://www.rshughes.com/c/Hand-Pads/1152/",
        // "https://www.rshughes.com/c/Sanding-Blocks/1159/",
        // "https://www.rshughes.com/c/Sanding-Sponges/1166/",
        // "https://www.rshughes.com/c/Steel-Wool/1170/",
        // "https://www.rshughes.com/c/Deburring-Discs/1113/",
        // "https://www.rshughes.com/c/Fiber-Discs/1143/",
        // "https://www.rshughes.com/c/Flap-Discs/1144/",
        // "https://www.rshughes.com/c/Hook-Loop-Discs/1153/",
        // "https://www.rshughes.com/c/Lapping-Film-Discs-Disc-Rolls/1155/",
        // "https://www.rshughes.com/c/PSA-Discs-Disc-Rolls/1157/",
        // "https://www.rshughes.com/c/Sanding-Disc-Sets/1161/",
        // "https://www.rshughes.com/c/Sanding-Disc-Backing-Pads/1174/",
        // "https://www.rshughes.com/c/Sanding-Disc-Hardware/1175/",
        // "https://www.rshughes.com/c/Sanding-Disc-Roll-Dispensers/1176/",
        // "https://www.rshughes.com/c/Sanding-Sheet-Roll-Accessories/1162/",
        // "https://www.rshughes.com/c/Sanding-Sheet-Roll-Sets/1163/",
        // "https://www.rshughes.com/c/Sanding-Sheet-Holders/1164/",
        // "https://www.rshughes.com/c/Sanding-Sheets-Rolls/1165/",
        // "https://www.rshughes.com/c/Shop-Rolls/1169/",
        // "https://www.rshughes.com/c/Sanding-Star-Sets/1167/",
        // "https://www.rshughes.com/c/Sanding-Stars/1168/",
        // "https://www.rshughes.com/c/Spiral-Bands/1132/",
        // "https://www.rshughes.com/c/Deburring-Accessories/1111/",
        // "https://www.rshughes.com/c/Deburring-Disc-Wheel-Sets/1112/",
        // "https://www.rshughes.com/c/Deburring-Discs/1113/",
        // "https://www.rshughes.com/c/Deburring-Rolls/1114/",
        // "https://www.rshughes.com/c/Deburring-Wheels/1115/",
        // "https://www.rshughes.com/c/Disc-Pads/715/",
        // "https://www.rshughes.com/c/Diamond-Dressers/1139/",
        // "https://www.rshughes.com/c/Dresser-Holders/1140/",
        // "https://www.rshughes.com/c/Dressing-Sticks/1141/",
        // "https://www.rshughes.com/c/Truing-Tools/1173/",
        // "https://www.rshughes.com/c/Cutoff-Wheels/1135/",
        // "https://www.rshughes.com/c/Deburring-Wheels/1115/",
        // "https://www.rshughes.com/c/Depressed-Center-Wheels/1138/",
        // "https://www.rshughes.com/c/Surface-Grinding-Wheels/1171/",
        // "https://www.rshughes.com/c/Tool-Cutter-Grinding-Wheels/1172/",
        // "https://www.rshughes.com/c/Hand-Hones/1119/",
        // "https://www.rshughes.com/c/Hand-Laps/1120/",
        // "https://www.rshughes.com/c/Lapping-Film-Discs-Disc-Rolls/1155/",
        // "https://www.rshughes.com/c/Lapping-Film-Sheets-Rolls/1156/",
        // "https://www.rshughes.com/c/Acrylic-Adhesives/2008/",
        // "https://www.rshughes.com/c/Activators-Primers-Etchants/2009/",
        // "https://www.rshughes.com/c/Adhesive-Sealants/2011/",
        // "https://www.rshughes.com/c/Conductive-Adhesives/2015/",
        // "https://www.rshughes.com/c/Contact-Construction-Adhesives/2016/",
        // "https://www.rshughes.com/c/Cyanoacrylate-Adhesives/2017/",
        // "https://www.rshughes.com/c/Epoxy-Adhesives/2021/",
        // "https://www.rshughes.com/c/Gasket-Sealants-Adhesives/2025/",
        // "https://www.rshughes.com/c/Hot-Melt-Adhesives/2027/",
        // "https://www.rshughes.com/c/Methacrylate-Adhesives/2030/",
        // "https://www.rshughes.com/c/Product-Consumer-Packaging-Adhesives/2033/",
        // "https://www.rshughes.com/c/Retaining-Compounds/2035/",
        // "https://www.rshughes.com/c/Spray-Adhesives/2037/",
        // "https://www.rshughes.com/c/Threadlockers/2041/",
        // "https://www.rshughes.com/c/Urethane-Polyurethane-Adhesives/2043/",
        // "https://www.rshughes.com/c/Adhesive-Sealant-Guns-And-Applicators/2014/",
        // "https://www.rshughes.com/c/Adhesive-Dispensing-Robots/2104/",
        // "https://www.rshughes.com/c/Robot-Parts-Accessories/2105/",
        // "https://www.rshughes.com/c/Adapters-Fittings/2044/",
        // "https://www.rshughes.com/c/Adhesion-Test-Measurement/2097/",
        // "https://www.rshughes.com/c/Adhesive-Kits-Accessory-Assemblies/2070/",
        // "https://www.rshughes.com/c/Bottles-Bottle-Caps/2052/",
        // "https://www.rshughes.com/c/Cartridge-Plungers/2053/",
        // "https://www.rshughes.com/c/Controllers-Reservoirs-Dispense-Valves/2056/",
        // "https://www.rshughes.com/c/Electrical-Power-Accessories/2064/",
        // "https://www.rshughes.com/c/Hand-Pumps/2065/",
        // "https://www.rshughes.com/c/Mixing-Spreading-Tools/2078/",
        // "https://www.rshughes.com/c/Replacement-Knobs-Reservoir-Parts/2087/",
        // "https://www.rshughes.com/c/Stands-Mounting-Brackets-Mounting-Hardware/2094/",
        // "https://www.rshughes.com/c/Syringe-Components-Kits/2095/",
        // "https://www.rshughes.com/c/Temperature-Modules/2096/",
        // "https://www.rshughes.com/c/Tip-Caps/2098/",
        // "https://www.rshughes.com/c/Tubing-Tubing-Systems/2099/",
        // "https://www.rshughes.com/c/Dispensing-Needles-Syringes/2019/",
        // "https://www.rshughes.com/c/Dispensing-Systems-Product-Kits/2020/",
        // "https://www.rshughes.com/c/Hot-Melt-Applicators/2028/",
        // "https://www.rshughes.com/c/Conveyors-Conveyor-Belts/2057/",
        // "https://www.rshughes.com/c/Light-Curing-Adhesive-Dispenser-Accessories/2073/",
        // "https://www.rshughes.com/c/Light-Curing-Adhesive-Dispensers/2074/",
        // "https://www.rshughes.com/c/Light-Curing-System-Accessories/2075/",
        // "https://www.rshughes.com/c/Light-Curing-Systems-Light-Sources/2076/",
        // "https://www.rshughes.com/c/Light-Curtains-Chambers/2077/",
        // "https://www.rshughes.com/c/Process-Monitoring-Interface-Systems-Accessories/2084/",
        // "https://www.rshughes.com/c/Air-Caps/2047/",
        // "https://www.rshughes.com/c/Atomizing-Heads-Sets/2050/",
        // "https://www.rshughes.com/c/Cups-Lids/2058/",
        // "https://www.rshughes.com/c/Digital-Spray-Valve-Controllers-Pumps/2061/",
        // "https://www.rshughes.com/c/Holders-Mounting-Accessories/2066/",
        // "https://www.rshughes.com/c/Hoses-Tubing/2068/",
        // "https://www.rshughes.com/c/Needle-Assemblies/2079/",
        // "https://www.rshughes.com/c/Parts-Kits-Tools-Small-Parts/2082/",
        // "https://www.rshughes.com/c/Seals-Gaskets-Diaphragms/2088/",
        // "https://www.rshughes.com/c/Spray-Gun-Bodies-Manifolds/2090/",
        // "https://www.rshughes.com/c/Spray-Guns-Turbine-Packages/2092/",
        // "https://www.rshughes.com/c/Switches-Trigger-Knobs/2072/",
        // "https://www.rshughes.com/c/Valves/2103/",
        // "https://www.rshughes.com/c/Tips-Nozzles/2042/",
        // "https://www.rshughes.com/c/Adhesive-Sealants/2011/",
        // "https://www.rshughes.com/c/Asphalt-Concrete-Sealants/2012/",
        // "https://www.rshughes.com/c/Caulk/2013/",
        // "https://www.rshughes.com/c/Encapsulating-Potting-Compounds/2032/",
        // "https://www.rshughes.com/c/Fillers/2023/",
        // "https://www.rshughes.com/c/Firestop-Sealants/2024/",
        // "https://www.rshughes.com/c/Gasket-Adhesives-Sealants/2026/",
        // "https://www.rshughes.com/c/Polyurethane-Foam/2031/",
        // "https://www.rshughes.com/c/Retaining-Compounds/2035/",
        // "https://www.rshughes.com/c/Silicone-Sealants/2036/",
        // "https://www.rshughes.com/c/Liquid-Thread-Sealants/2106/",
        // "https://www.rshughes.com/c/Thread-Sealant-Tapes/3028/",
        // "https://www.rshughes.com/c/Threadlockers/2041/",
        // "https://www.rshughes.com/c/Aerospace-Chemicals-Wipes/6008/",
        // "https://www.rshughes.com/c/Chemical-Indicators/6012/",
        // "https://www.rshughes.com/c/Air-Dusters-Electronics-Cleaners/6009/",
        // "https://www.rshughes.com/c/Carpet-Fabric-Cleaners/6022/",
        // "https://www.rshughes.com/c/Cleaners-Degreasers-Solvents/6023/",
        // "https://www.rshughes.com/c/Disinfectants-Bathroom-Cleaners-Odor-Control/6024/",
        // "https://www.rshughes.com/c/Floor-Wood-Cleaners/6025/",
        // "https://www.rshughes.com/c/Glass-Cleaners/6026/",
        // "https://www.rshughes.com/c/Hand-Cleaners-Sanitizers/6027/",
        // "https://www.rshughes.com/c/Lime-Rust-Removers/6028/",
        // "https://www.rshughes.com/c/Metal-Cleaners-Stone-Care/6029/",
        // "https://www.rshughes.com/c/Insecticides/6015/",
        // "https://www.rshughes.com/c/Paint-Thinners-Removers-Strippers/6007/",
        // "https://www.rshughes.com/c/Anti-Seize-Lubricants/6010/",
        // "https://www.rshughes.com/c/Cable-Pulling-Lubricants/6011/",
        // "https://www.rshughes.com/c/Greases/6014/",
        // "https://www.rshughes.com/c/Metalworking-Fluids/6016/",
        // "https://www.rshughes.com/c/Oils/6017/",
        // "https://www.rshughes.com/c/Penetrants-Multi-Purpose-Lubricants/6019/",
        // "https://www.rshughes.com/c/Release-Agents/6020/",
        // "https://www.rshughes.com/c/Rust-Inhibitors-Corrosion-Protective-Coatings/4021/",
        //
        //
        // "https://www.rshughes.com/c/Cable-Wire-Marker-Carriers/7132/",
        // "https://www.rshughes.com/c/Cable-Wire-Marker-Sleeves-Clips/7133/",
        // "https://www.rshughes.com/c/Cable-Clips-Stackers-Mounting-Bases/5055/",
        // "https://www.rshughes.com/c/Cable-Covers/5056/",
        // "https://www.rshughes.com/c/Cable-Mounting-Brackets/5058/",
        // "https://www.rshughes.com/c/Cable-Tie-Guns/5064/",
        // "https://www.rshughes.com/c/Cable-Ties-Straps/5065/",
        // "https://www.rshughes.com/c/Cable-Cleaning-Preparation-Kits/5054/",
        // "https://www.rshughes.com/c/Cable-Grounding-Kits/5141/",
        // "https://www.rshughes.com/c/Cable-Grounding-Straps-Braids/5142/",
        // "https://www.rshughes.com/c/Constant-Force-Springs/5148/",
        // "https://www.rshughes.com/c/Cable-Breakout-Boots/5139/",
        // "https://www.rshughes.com/c/Cable-End-Caps/5140/",
        // "https://www.rshughes.com/c/Cable-Protection-Sealing-Kits/5143/",
        // "https://www.rshughes.com/c/Continuous-Printer-Heat-Shrink-Tubing/7136/",
        // "https://www.rshughes.com/c/Electrical-Resin-Guns-Accessories/5095/",
        // "https://www.rshughes.com/c/Electrical-Resins/5163/",
        // "https://www.rshughes.com/c/Heat-Shrink-Tubing-Insulation/5165/",
        // "https://www.rshughes.com/c/Insertion-Seals/5167/",
        // "https://www.rshughes.com/c/Cable-Repair-Kits/5144/",
        // "https://www.rshughes.com/c/Cable-Repair-Sleeves-Structural-Material/5145/",
        // "https://www.rshughes.com/c/Barrel-Connectors/5050/",
        // "https://www.rshughes.com/c/Cable-Splice-Accessories/5061/",
        // "https://www.rshughes.com/c/Cable-Splices/5062/",
        // "https://www.rshughes.com/c/Cable-Splicing-Kits/5063/",
        // "https://www.rshughes.com/c/Electrical-Resin-Guns-Accessories/5095/",
        // "https://www.rshughes.com/c/Electrical-Resins/5163/",
        // "https://www.rshughes.com/c/Transition-Connectors/5131/",
        // "https://www.rshughes.com/c/Electric-Non-Adhesive-Tape-Dispensers/5023/",
        // "https://www.rshughes.com/c/Electrical-Insulating-Blanket-Kits-Accessories/8036/",
        // "https://www.rshughes.com/c/Electrical-Insulating-Blankets/8037/",
        // "https://www.rshughes.com/c/Conductive-Tapes/3035/",
        // "https://www.rshughes.com/c/Copper-Tapes/3037/",
        // "https://www.rshughes.com/c/Electrical-Marking-Tapes/3044/",
        // "https://www.rshughes.com/c/Insulating-Tapes/3050/",
        // "https://www.rshughes.com/c/Static-Control-Tapes/3060/",
        // "https://www.rshughes.com/c/Water-Contact-Indicator-Tapes/3066/",
        // "https://www.rshughes.com/c/Circuit-Coolers/5014/",
        // "https://www.rshughes.com/c/Continuity-Tester-LCR-Meter-Parts/5068/",
        // "https://www.rshughes.com/c/Continuity-Testers/5069/",
        // "https://www.rshughes.com/c/ESD-Static-Meters-Testing-Equipment/5091/",
        // "https://www.rshughes.com/c/LCR-Meters/5109/",
        // "https://www.rshughes.com/c/Air-Dusters-Electronics-Cleaners/6009/",
        // "https://www.rshughes.com/c/Electronics-Cleaning-Brushes-Brush-Kits/5026/",
        // "https://www.rshughes.com/c/Electronics-Cleaning-Swabs/5027/",
        // "https://www.rshughes.com/c/Electronics-Cleaning-Wipes/5028/",
        // "https://www.rshughes.com/c/ESD-Anti-Static-Cleaners-Coatings/5017/",
        // "https://www.rshughes.com/c/ESD-Anti-Static-Lotion/5250/",
        // "https://www.rshughes.com/c/ESD-Anti-Static-Bags/5073/",
        // "https://www.rshughes.com/c/ESD-Anti-Static-Dessicant-Humidity-Indicator-Cards/5076/",
        // "https://www.rshughes.com/c/ESD-Anti-Static-Packing-Foam-Film-Wire-Frames/5080/",
        // "https://www.rshughes.com/c/ESD-Anti-Static-Storage-Shipping-Containers/5082/",
        // "https://www.rshughes.com/c/ESD-Package-Sealers/5090/",
        // "https://www.rshughes.com/c/ESD-Anti-Static-Tags-Document-Holders/5083/",
        // "https://www.rshughes.com/c/ESD-Anti-Static-Training-Booklets-Software-DVDs/5084/",
        // "https://www.rshughes.com/c/ESD-Anti-Static-Floor-Tiles-Carpets-Furniture-Covers/5077/",
        // "https://www.rshughes.com/c/ESD-Anti-Static-Mats/5079/",
        // "https://www.rshughes.com/c/ESD-Grounding-Cords/5155/",
        // "https://www.rshughes.com/c/ESD-Grounding-Kits/5156/",
        // "https://www.rshughes.com/c/ESD-Grounding-Shoe-Accessories-Disposable-Footwear/5088/",
        // "https://www.rshughes.com/c/ESD-Grounding-Wrist-Straps-Cord-Sets/5089/",
        // "https://www.rshughes.com/c/ESD-Snaps-Snap-Tools-Small-Hardware/5160/",
        // "https://www.rshughes.com/c/Continuity-Tester-LCR-Meter-Parts/5068/",
        // "https://www.rshughes.com/c/Continuity-Testers/5069/",
        // "https://www.rshughes.com/c/ESD-Continuous-Workstation-Monitors/5154/",
        // "https://www.rshughes.com/c/ESD-Monitor-Meter-Accessories/5159/",
        // "https://www.rshughes.com/c/ESD-Static-Meters-Testing-Equipment/5091/",
        // "https://www.rshughes.com/c/LCR-Meters/5109/",
        // "https://www.rshughes.com/c/ESD-Anti-Static-Brushes/5074/",
        // "https://www.rshughes.com/c/ESD-Anti-Static-Cleaners-Coatings/5017/",
        // "https://www.rshughes.com/c/ESD-Anti-Static-Refillable-Containers/5081/",
        // "https://www.rshughes.com/c/ESD-Anti-Static-Tool-Organizers-And-Kitting-Trays/5078/",
        // "https://www.rshughes.com/c/ESD-Anti-Static-Trash-Cans-Liners/5085/",
        // "https://www.rshughes.com/c/ESD-Anti-Static-Vacuums-And-Accessories/5086/",
        // "https://www.rshughes.com/c/ESD-Anti-Static-Gloves/5151/",
        // "https://www.rshughes.com/c/ESD-Anti-Static-Jackets-Lab-Coats-Shirts/5152/",
        // "https://www.rshughes.com/c/ESD-Grounding-Shoe-Accessories-Disposable-Footwear/5088/",
        // "https://www.rshughes.com/c/ESD-Grounding-Wrist-Straps-Cord-Sets/5089/",
        // "https://www.rshughes.com/c/Ionizer-Replacement-Parts-Accessories/5105/",
        // "https://www.rshughes.com/c/Ionizers-Ion-Test-Meters-Kits/5106/",
        // "https://www.rshughes.com/c/Static-Discharge-Grounding-Reels/9804/",
        // "https://www.rshughes.com/c/Lockout-Tagout-Labels/7090/",
        // "https://www.rshughes.com/c/Lockout-Tagout-Tags/7092/",
        // "https://www.rshughes.com/c/Key-Padlock-Cabinets-Stations-Storage/8186/",
        // "https://www.rshughes.com/c/Lockout-Tagout-Device-Cabinets-Stations-Storage/8195/",
        // "https://www.rshughes.com/c/Lockout-Tagout-Training-Materials/8200/",
        // "https://www.rshughes.com/c/Circuit-Breaker-Fuse-Lockout-Devices-Systems/8123/",
        // "https://www.rshughes.com/c/Electrical-Plug-Switch-Lockout-Devices/8145/",
        // "https://www.rshughes.com/c/Group-Lockout-Boxes/8171/",
        // "https://www.rshughes.com/c/Lockout-Tagout-Accessories/8192/",
        // "https://www.rshughes.com/c/Lockout-Tagout-Hasps/8197/",
        // "https://www.rshughes.com/c/Lockout-Tagout-Kits/8199/",
        // "https://www.rshughes.com/c/Pneumatic-Lockout-Devices/8217/",
        // "https://www.rshughes.com/c/Valve-Lockout-Devices/8262/",
        // "https://www.rshughes.com/c/Lockout-Tagout-Equipment-Shutoff-Signs/9163/",
        // "https://www.rshughes.com/c/Combination-Padlocks/8304/",
        // "https://www.rshughes.com/c/Keyed-Safety-Padlocks/8189/",
        // "https://www.rshughes.com/c/Padlock-Kits/8213/",
        // "https://www.rshughes.com/c/Potting-Encapsulating-Compounds/2006/",
        // "https://www.rshughes.com/c/Conductive-Overcoat-Pens/5015/",
        // "https://www.rshughes.com/c/Desoldering-Wicks-Braids/5016/",
        // "https://www.rshughes.com/c/Heat-Gun-Torch-Accessories/5101/",
        // "https://www.rshughes.com/c/Heat-Guns-Torches/5102/",
        // "https://www.rshughes.com/c/Liquid-Solder-Mask/5034/",
        // "https://www.rshughes.com/c/Lead-Free-Solder-Bars/5115/",
        // "https://www.rshughes.com/c/Lead-Solder-Bars/5112/",
        // "https://www.rshughes.com/c/Lead-Free-Solder-Pastes/5116/",
        // "https://www.rshughes.com/c/Lead-Solder-Pastes/5113/",
        // "https://www.rshughes.com/c/Lead-Solder-Wires/5114/",
        // "https://www.rshughes.com/c/Lead-Free-Solder-Wires/5117/",
        // "https://www.rshughes.com/c/Flux-Dispensers/5097/",
        // "https://www.rshughes.com/c/Flux-Removers/5098/",
        // "https://www.rshughes.com/c/Solder-Flux-Thinners/5119/",
        // "https://www.rshughes.com/c/Solder-Fume-Extractor-Adapters-Fittings-Small-Parts/5178/",
        // "https://www.rshughes.com/c/Solder-Fume-Extractor-Clips-Brackets-Mounting-Accessories/5179/",
        // "https://www.rshughes.com/c/Solder-Fume-Extractor-Filters/5180/",
        // "https://www.rshughes.com/c/Solder-Fume-Extractor-Hoods/5181/",
        // "https://www.rshughes.com/c/Solder-Fume-Extractor-Kits/5182/",
        // "https://www.rshughes.com/c/Solder-Fume-Extractor-Motors-Blowers-And-Parts/5183/",
        // "https://www.rshughes.com/c/Solder-Fume-Extractor-Nozzles-Hoses-Arms/5184/",
        // "https://www.rshughes.com/c/Solder-Fume-Extractor-Packaging-Documentation/5185/",
        // "https://www.rshughes.com/c/Solder-Fume-Extractor-Power-Accessories/5186/",
        // "https://www.rshughes.com/c/Solder-Fume-Extractor-Top-Covers/5187/",
        // "https://www.rshughes.com/c/Solder-Fume-Extractor-Systems/5121/",
        // "https://www.rshughes.com/c/Soldering-Spatulas/5043/",
        // "https://www.rshughes.com/c/Soldering-Desoldering-Iron-Cleaning-And-Tinning-Supplies/5122/",
        // "https://www.rshughes.com/c/Soldering-Rework-Station-Power-Supply-Units/5188/",
        // "https://www.rshughes.com/c/Soldering-Iron-Stands-Stand-Accessories/5190/",
        // "https://www.rshughes.com/c/Soldering-Rework-Desoldering-Irons-Handpieces/5191/",
        // "https://www.rshughes.com/c/Soldering-Rework-Desoldering-Stations/5192/",
        // "https://www.rshughes.com/c/Soldering-Rework-Desoldering-Part-Accessory-Kits/5124/",
        // "https://www.rshughes.com/c/Soldering-Rework-Desoldering-Parts-Accessories/5125/",
        // "https://www.rshughes.com/c/Rework-Nozzles-Nozzle-Kits/5174/",
        // "https://www.rshughes.com/c/Soldering-Desoldering-Tips-Cartridges/5189/",
        // "https://www.rshughes.com/c/Vacuum-Pickup-Tool-Parts/5134/",
        // "https://www.rshughes.com/c/Vacuum-Pickup-Tools/5135/",
        // "https://www.rshughes.com/c/Air-Filters/9701/",
        // "https://www.rshughes.com/c/Chemical-Filters/9703/",
        // "https://www.rshughes.com/c/Filter-Housings-Accessories/9704/",
        // "https://www.rshughes.com/c/Indoor-Air-Purifiers/9705/",
        // "https://www.rshughes.com/c/Industrial-Fans/10061/",
        // "https://www.rshughes.com/c/Water-Filters/9702/",
        // "https://www.rshughes.com/c/Broom-Brush-Handles/9590/",
        // "https://www.rshughes.com/c/Broom-Brush-Heads/9591/",
        // "https://www.rshughes.com/c/Broom-Brush-Kits/9592/",
        // "https://www.rshughes.com/c/Broom-Braces-Handle-Adapters/9593/",
        // "https://www.rshughes.com/c/Brooms-Dust-Brushes/9594/",
        // "https://www.rshughes.com/c/Dust-Pans/9598/",
        // "https://www.rshughes.com/c/Scrub-Brushes/9603/",
        // "https://www.rshughes.com/c/Application-Finishing-Brush-Heads/9587/",
        // "https://www.rshughes.com/c/Application-Finishing-Brush-Kits/9588/",
        // "https://www.rshughes.com/c/Broom-Brush-Handles/9590/",
        // "https://www.rshughes.com/c/Finishing-Tools/9599/",
        // "https://www.rshughes.com/c/Bucket-Cart-Accessories/9595/",
        // "https://www.rshughes.com/c/Bucket-Cart-Systems/9596/",
        // "https://www.rshughes.com/c/Buckets/9597/",
        // "https://www.rshughes.com/c/Mop-Handles/9600/",
        // "https://www.rshughes.com/c/Mop-Heads-Frames/9601/",
        // "https://www.rshughes.com/c/Mop-Pads-Covers/9602/",
        // "https://www.rshughes.com/c/Wet-Mops/9608/",
        // "https://www.rshughes.com/c/Sponges/9573/",
        // "https://www.rshughes.com/c/Squeegees-Refills/9574/",
        // "https://www.rshughes.com/c/Vacuums/9607/",
        // "https://www.rshughes.com/c/Vacuum-Accessories/9606/",
        // "https://www.rshughes.com/c/Cleaning-Wipes/9542/",
        // "https://www.rshughes.com/c/Huck-Towels/9555/",
        // "https://www.rshughes.com/c/Reclaimed-Rags/9614/",
        // "https://www.rshughes.com/c/Shop-Towels/9571/",
        // "https://www.rshughes.com/c/Cleaning-Container-Mountings/9541/",
        // "https://www.rshughes.com/c/Blade-Disposal/9544/",
        // "https://www.rshughes.com/c/Disposal-Units-Accessories/9543/",
        // "https://www.rshughes.com/c/Liquid-Hygiene-Product-Dispensers/9557/",
        // "https://www.rshughes.com/c/Paper-Hygiene-Product-Dispensers/9563/",
        // "https://www.rshughes.com/c/Personal-Hygiene-Material-Dispenser-Accessories/9565/",
        // "https://www.rshughes.com/c/Wiper-Dispensers/9586/",
        // "https://www.rshughes.com/c/Bathroom-Tissue/9534/",
        // "https://www.rshughes.com/c/Facial-Tissue/9547/",
        // "https://www.rshughes.com/c/Feminine-Hygiene-Products/9698/",
        // "https://www.rshughes.com/c/Foodservice-Napkins/9551/",
        // "https://www.rshughes.com/c/Paper-Towels/9564/",
        // "https://www.rshughes.com/c/Skin-Care-Products/9572/",
        // "https://www.rshughes.com/c/Toilet-Seat-Covers/9578/",
        // "https://www.rshughes.com/c/Urinal-Accessories/9699/",
        // "https://www.rshughes.com/c/Air-Fresheners-Air-Filters/9507/",
        //
        //
        // "https://www.rshughes.com/c/Storage-Cabinets/9539/",
        // "https://www.rshughes.com/c/Louvered-Racks-And-Panels/9518/",
        // "https://www.rshughes.com/c/Safety-Guards-Barriers/9567/",
        // "https://www.rshughes.com/c/Storage-Bin-Racks/9549/",
        // "https://www.rshughes.com/c/Wire-Shelf-Bin-Organizers/9550/",
        // "https://www.rshughes.com/c/Document-Storage-Boxes/9515/",
        // "https://www.rshughes.com/c/Label-Holders/598/",
        // "https://www.rshughes.com/c/Organizers-Protective-Cases/9521/",
        // "https://www.rshughes.com/c/Shelving/9525/",
        // "https://www.rshughes.com/c/Attached-Lid-Containers/9533/",
        // "https://www.rshughes.com/c/shipping:bin-storage-containers:jumbo-open-top-bin-boxes/93/",
        // "https://www.rshughes.com/c/Grid-Containers/9517/",
        // "https://www.rshughes.com/c/Cabinet-Drawers-Shelves-Accessories/9537/",
        // "https://www.rshughes.com/c/shipping:bin-storage-containers:stack-nest-containers/156/",
        // "https://www.rshughes.com/c/Straight-Wall-Containers/9577/",
        // "https://www.rshughes.com/c/Totes-Lids/9581/",
        // "https://www.rshughes.com/c/shipping:bin-storage-containers:brute-totes/31/",
        // "https://www.rshughes.com/c/Tubs/9584/",
        // "https://www.rshughes.com/c/Disposable-Food-Service-Supplies/9616/",
        // "https://www.rshughes.com/c/Facilities-Training-Materials/9502/",
        // "https://www.rshughes.com/c/Cord-Cable-Reels/9803/",
        // "https://www.rshughes.com/c/Hose-Reel-Accessories/9802/",
        // "https://www.rshughes.com/c/Hose-Reels/9801/",
        // "https://www.rshughes.com/c/Static-Discharge-Grounding-Reels/9804/",
        // "https://www.rshughes.com/c/Welding-Cable-Reels/9806/",
        // "https://www.rshughes.com/c/Welding-Hose-Reels/9805/",
        // "https://www.rshughes.com/c/shipping:shipping-room-supplies:trucks-carts/169/",
        // "https://www.rshughes.com/c/Lifting-Slings/9821/",
        // "https://www.rshughes.com/c/Carts/9540/",
        // "https://www.rshughes.com/c/Dollies/9545/",
        // "https://www.rshughes.com/c/Hand-Trucks/9554/",
        // "https://www.rshughes.com/c/Lift-Jacks/9556/",
        // "https://www.rshughes.com/c/Platform-Trucks/9566/",
        // "https://www.rshughes.com/c/Tote-Caddies/9579/",
        // "https://www.rshughes.com/c/Truck-Lids/9582/",
        // "https://www.rshughes.com/c/Replacement-Lifting-Cables-Wire/9822/",
        // "https://www.rshughes.com/c/Rigging-Hardware/9825/",
        // "https://www.rshughes.com/c/Tie-Downs/9824/",
        // "https://www.rshughes.com/c/Towing-Products/9823/",
        // "https://www.rshughes.com/c/Clipboards-Binders/9511/",
        // "https://www.rshughes.com/c/Industrial-Office-Chairs/9690/",
        // "https://www.rshughes.com/c/Writing-Implements/9530/",
        // "https://www.rshughes.com/c/Writing-Paper-Notebooks/9531/",
        // "https://www.rshughes.com/c/Badge-Vehicle-Permit-Sleeves/8415/",
        // "https://www.rshughes.com/c/Lanyards-Retractable-Badge-Holders-Strap-Clips/8423/",
        // "https://www.rshughes.com/c/ID-Badges-Badge-Inserts/8353/",
        // "https://www.rshughes.com/c/Combination-Padlocks/8304/",
        // "https://www.rshughes.com/c/Keyed-Safety-Padlocks/8189/",
        // "https://www.rshughes.com/c/Padlock-Kits/8213/",
        // "https://www.rshughes.com/c/Parking-Permit-Labels/7103/",
        // "https://www.rshughes.com/c/Parking-Violation-Labels/7105/",
        // "https://www.rshughes.com/c/Pre-Printed-Vehicle-Hang-Tags/8075/",
        // "https://www.rshughes.com/c/Badge-Holders-Lanyards/5072/",
        // "https://www.rshughes.com/c/Air-Horns/8550/",
        // "https://www.rshughes.com/c/Safety-Beacon-Light-Accessories/8243/",
        // "https://www.rshughes.com/c/Safety-Beacons-Flash-Batons-Light-Kits/8244/",
        // "https://www.rshughes.com/c/Communication-Headset-Audio-Device-Adapter-Cables/8416/",
        // "https://www.rshughes.com/c/Communication-Headset-Parts-Accessories/8417/",
        // "https://www.rshughes.com/c/Communication-Headset-Power-Adapters-Battery-Packs-Chargers/8418/",
        // "https://www.rshughes.com/c/Communication-Headsets-Systems/8419/",
        // "https://www.rshughes.com/c/Earplugs-Protective-Earmuffs/8342/",
        // "https://www.rshughes.com/c/Megaphones/8424/",
        // "https://www.rshughes.com/c/Microphone-Accessories/8425/",
        // "https://www.rshughes.com/c/Microphones/8426/",
        // "https://www.rshughes.com/c/Radios-Speakers/10059/",
        // "https://www.rshughes.com/c/Safety-Mirrors/8391/",
        // "https://www.rshughes.com/c/Bollard-Posts-Accessories/9620/",
        // "https://www.rshughes.com/c/Dockplates/9514/",
        // "https://www.rshughes.com/c/Portable-Shelters/9621/",
        // "https://www.rshughes.com/c/Ramps/9523/",
        // "https://www.rshughes.com/c/Reinforcement-Patches/9524/",
        // "https://www.rshughes.com/c/Social-Distancing-Partitions/9622/",
        // "https://www.rshughes.com/c/Work-Stations-Workbenches/10055/",
        // "https://www.rshughes.com/c/Batteries/9611/",
        // "https://www.rshughes.com/c/Flashlights-Lanterns/9612/",
        // "https://www.rshughes.com/c/Headlamps/9609/",
        // "https://www.rshughes.com/c/Power-Accessories/9610/",
        // "https://www.rshughes.com/c/Barcode-Scanner-Accessories/7021/",
        // "https://www.rshughes.com/c/Barcode-Scanners-Kits/7022/",
        // "https://www.rshughes.com/c/Label-Attachment-System-Accessories/7030/",
        // "https://www.rshughes.com/c/Label-Attachment-Systems-Kits/7031/",
        // "https://www.rshughes.com/c/Label-Dispenser-Accessories/7032/",
        // "https://www.rshughes.com/c/Label-Dispensers/7033/",
        // "https://www.rshughes.com/c/Arrow-Footprint-Marking-Labels/7057/",
        // "https://www.rshughes.com/c/Marking-Dots-Corner-Marking-Labels/7099/",
        // "https://www.rshughes.com/c/Inventory-Control-Identification-Labels/7029/",
        // "https://www.rshughes.com/c/Hang-Tabs/7077/",
        // "https://www.rshughes.com/c/Mailing-Labels/7095/",
        // "https://www.rshughes.com/c/Motivational-Labels/7042/",
        // "https://www.rshughes.com/c/Pipe-Marker-Accessories-Mounting-Brackets/7107/",
        // "https://www.rshughes.com/c/Self-Adhesive-Pipe-Markers/7117/",
        // "https://www.rshughes.com/c/Snap-On-Pipe-Markers/7118/",
        // "https://www.rshughes.com/c/Strap-On-Pipe-Markers/7119/",
        // "https://www.rshughes.com/c/Wrap-Around-Pipe-Markers/7130/",
        // "https://www.rshughes.com/c/Dot-Matrix-Printer-Labels/7070/",
        // "https://www.rshughes.com/c/Laser-Ink-Jet-Printable-Labels/7087/",
        // "https://www.rshughes.com/c/Continuous-Thermal-Transfer-Printer-Heat-Shrink-Tubing/7137/",
        // "https://www.rshughes.com/c/Continuous-Thermal-Transfer-Printer-Label-Cartridges/7138/",
        // "https://www.rshughes.com/c/Continuous-Thermal-Transfer-Printer-Label-Rolls/7139/",
        // "https://www.rshughes.com/c/Die-Cut-Thermal-Transfer-Printer-Cartridges/7140/",
        // "https://www.rshughes.com/c/Die-Cut-Thermal-Transfer-Printer-Label-Rolls/7141/",
        // "https://www.rshughes.com/c/Die-Cut-Thermal-Transfer-Printer-Sleeves/7142/",
        // "https://www.rshughes.com/c/Chemical-Hazard-Right-To-Know-Labels/7066/",
        // "https://www.rshughes.com/c/Fire-Extinguisher-Labels/7144/",
        // "https://www.rshughes.com/c/Fire-Hazard-Labels/7073/",
        // "https://www.rshughes.com/c/Hazardous-Area-Labels/7080/",
        // "https://www.rshughes.com/c/Health-Sanitation-Waste-Labels/7081/",
        // "https://www.rshughes.com/c/Laser-Hazard-Labels/7088/",
        // "https://www.rshughes.com/c/Electrical-Safety-Labels/7143/",
        // "https://www.rshughes.com/c/Lockout-Tagout-Labels/7090/",
        // "https://www.rshughes.com/c/Machine-Equipment-Safety-Labels/7093/",
        // "https://www.rshughes.com/c/Circuit-Board-Inspection-Labels/7135/",
        // "https://www.rshughes.com/c/Inspection-Quality-Control-Labels/7147/",
        // "https://www.rshughes.com/c/Maintenance-Calibration-Labels/7149/",
        // "https://www.rshughes.com/c/Marine-Labels/7098/",
        // "https://www.rshughes.com/c/Radiation-Hazard-Labels/7116/",
        // "https://www.rshughes.com/c/Access-Security-Labels/7056/",
        // "https://www.rshughes.com/c/Cable-Wire-Marker-Carriers/7131/",
        // "https://www.rshughes.com/c/Cable-Wire-Marker-Sleeves-Clips/7133/",
        // "https://www.rshughes.com/c/Gauge-Marking-Labels/7075/",
        // "https://www.rshughes.com/c/Number-Letter-Label-Kits/7150/",
        // "https://www.rshughes.com/c/Number-Letter-Labels/7151/",
        // "https://www.rshughes.com/c/Parking-Permit-Labels/7103/",
        // "https://www.rshughes.com/c/Parking-Violation-Labels/7105/",
        // "https://www.rshughes.com/c/Tamper-Evident-Seals/7126/",
        // "https://www.rshughes.com/c/Temperature-Indicator-Labels/7127/",
        // "https://www.rshughes.com/c/Tool-Equipment-Storage-Labels/7054/",
        // "https://www.rshughes.com/c/Laminator-Supplies/7037/",
        // "https://www.rshughes.com/c/Laminators/7038/",
        // "https://www.rshughes.com/c/Laminator-Pouches/7085/",
        // "https://www.rshughes.com/c/Laminator-Rolls/7086/",
        // "https://www.rshughes.com/c/Overlaminate/7102/",
        // "https://www.rshughes.com/c/Printer-Cases-Covers/7154/",
        // "https://www.rshughes.com/c/Printer-Cleaning-Tools/7155/",
        // "https://www.rshughes.com/c/Printer-Power-Accessories/7158/",
        // "https://www.rshughes.com/c/Printer-Protection-Repair-Services/7159/",
        // "https://www.rshughes.com/c/Printer-Replacement-Parts/7160/",
        // "https://www.rshughes.com/c/Printer-Storage-Media-Networking-Accessories/7161/",
        // "https://www.rshughes.com/c/Printing-Software/7162/",
        // "https://www.rshughes.com/c/Printer-Accessory-Kits/7111/",
        // "https://www.rshughes.com/c/Printer-Ribbons/7113/",
        // "https://www.rshughes.com/c/3D-Printers/7065/",
        // "https://www.rshughes.com/c/Desktop-Label-Printers/7069/",
        // "https://www.rshughes.com/c/Portable-Label-Printers/7108/",
        // "https://www.rshughes.com/c/Printer-Kits/7112/",
        // "https://www.rshughes.com/c/Blank-Cable-Marking-Tags/7059/",
        // "https://www.rshughes.com/c/Blank-General-Purpose-Tags/7060/",
        // "https://www.rshughes.com/c/Blank-Valve-Tags/7061/",
        // "https://www.rshughes.com/c/Inspection-Tags/7083/",
        // "https://www.rshughes.com/c/Maintenance-Repair-Tags/7096/",
        // "https://www.rshughes.com/c/Production-Status-Tags/7114/",
        // "https://www.rshughes.com/c/Pre-Printed-Vehicle-Hang-Tags/8075/",
        // "https://www.rshughes.com/c/Chemical-Hazard-Right-To-Know-Tags/7067/",

        // Safety
        "https://www.rshughes.com/c/Confined-Space-Tags/7068/",
        "https://www.rshughes.com/c/Energy-Source-Tags/7071/",
        "https://www.rshughes.com/c/Lockout-Tagout-Tags/7092/",
        "https://www.rshughes.com/c/Machine-Equipment-Safety-Tags/7094/",
        "https://www.rshughes.com/c/Ball-Chains/7058/",
        "https://www.rshughes.com/c/Grommets/7076/",
        "https://www.rshughes.com/c/Hooks-Key-Rings/7082/",
        "https://www.rshughes.com/c/Jack-Chain/7084/",
        "https://www.rshughes.com/c/Protective-Envelopes/7115/",
        "https://www.rshughes.com/c/Tag-Fastening-Tools/7120/",
        "https://www.rshughes.com/c/Tag-Stamping-Tools/7121/",
        "https://www.rshughes.com/c/Tag-Ties/7122/",
        "https://www.rshughes.com/c/Wires-Wire-Clamps/7129/",
        "https://www.rshughes.com/c/Tagging-System-Holders/7123/",
        "https://www.rshughes.com/c/Tagging-System-Inserts/7124/",
        "https://www.rshughes.com/c/Tagging-System-Kits/7125/",
        "https://www.rshughes.com/c/Blank-Valve-Tags/7061/",
        "https://www.rshughes.com/c/Pre-Printed-Valve-Tags/7109/",
        "https://www.rshughes.com/c/Acoustic-Absorbers/9901/",
        "https://www.rshughes.com/c/Aerospace-Thermal-Acoustic-Products/9905/",
        "https://www.rshughes.com/c/Impact-Protection-Cushioning/9906/",
        "https://www.rshughes.com/c/Shims-Spacers/9907/",
        "https://www.rshughes.com/c/Structural-Vibration-Damping/9904/",
        "https://www.rshughes.com/c/Additives/4008/",
        "https://www.rshughes.com/c/Test-Solutions/4023/",
        "https://www.rshughes.com/c/Abrasion-Resistant-Coatings/4007/",
        "https://www.rshughes.com/c/Aerospace-Coatings/4009/",
        "https://www.rshughes.com/c/Anti-Weld-Spatter-Coatings/4010/",
        "https://www.rshughes.com/c/Automotive-Marine-Coatings-Body-Fillers-Surface-Treatments/4011/",
        "https://www.rshughes.com/c/Chemical-Resistant-Coatings/4012/",
        "https://www.rshughes.com/c/Conversion-Coatings/4013/",
        "https://www.rshughes.com/c/Corrosion-Protective-Coatings-Rust-Inhibitors/4020/",
        "https://www.rshughes.com/c/Finish-Coatings/4015/",
        "https://www.rshughes.com/c/Overspray-Protective-Coatings/4017/",
        "https://www.rshughes.com/c/Pre-Treatments-Post-Treatments/4019/",
        "https://www.rshughes.com/c/Aerosol-Filling-Systems-Accessories/4024/",
        "https://www.rshughes.com/c/Aerosol-Striping-Systems-Stencil-Kits/4025/",
        "https://www.rshughes.com/c/Brush-Sets/4031/",
        "https://www.rshughes.com/c/Brushes/4032/",
        "https://www.rshughes.com/c/Buckets-Trays-Accessories/4033/",
        "https://www.rshughes.com/c/Mitts-Pads-Edgers/4034/",
        "https://www.rshughes.com/c/Roller-Kits-Covers-Frames-Poles/4035/",
        "https://www.rshughes.com/c/Masking-Tapes/3053/",
        "https://www.rshughes.com/c/Masking-Paper-Cloth-Film/3054/",
        "https://www.rshughes.com/c/Atomizing-Heads-Sets/2050/",
        "https://www.rshughes.com/c/Connection-Fittings/2055/",
        "https://www.rshughes.com/c/Cups-Lids/2058/",
        "https://www.rshughes.com/c/Digital-Spray-Valve-Controllers-Pumps/2061/",
        "https://www.rshughes.com/c/Hoses-Tubing/2068/",
        "https://www.rshughes.com/c/Knobs-Switches-Triggers/2071/",
        "https://www.rshughes.com/c/Mounting-Accessories-Holders/2067/",
        "https://www.rshughes.com/c/Needle-Assemblies/2079/",
        "https://www.rshughes.com/c/Parts-Kits-Tools-Small-Parts/2082/",
        "https://www.rshughes.com/c/Seals-Gaskets-Diaphragms/2088/",
        "https://www.rshughes.com/c/Spray-Gun-Bodies-Manifolds/2090/",
        "https://www.rshughes.com/c/Spray-Guns-Turbine-Packages/2092/",
        "https://www.rshughes.com/c/Valves/2103/",
        "https://www.rshughes.com/c/Marking-Pens/4016/",
        "https://www.rshughes.com/c/Paint-Primers/4027/",
        "https://www.rshughes.com/c/Paints/4028/",
        "https://www.rshughes.com/c/Stains-Marking-Fluids-Stencil-Ink/4030/",
        "https://www.rshughes.com/c/Confined-Space-Tags/7068/",
        "https://www.rshughes.com/c/Manhole-Collars/8204/",
        "https://www.rshughes.com/c/Body-Belt-Harness-Straps/8026/",
        "https://www.rshughes.com/c/Body-Harnesses/8027/",
        "https://www.rshughes.com/c/Cable-Rope-Grabs/8028/",
        "https://www.rshughes.com/c/Confined-Space-Entry-Rescue-Equipment/8130/",
        "https://www.rshughes.com/c/Manhole-Collars/8204/",
        "https://www.rshughes.com/c/Debris-Safety-Netting-Accessories/8499/",
        "https://www.rshughes.com/c/Anchorage-Connectors/8111/",
        "https://www.rshughes.com/c/Body-Belt-Harness-Straps/8026/",
        "https://www.rshughes.com/c/Cable-Guides-Sleeves/8120/",
        "https://www.rshughes.com/c/Fall-Protection-Equipment-Bags-Cases/8159/",
        "https://www.rshughes.com/c/Fall-Protection-Equipment-Parts-And-Accessories/8160/",
        "https://www.rshughes.com/c/Fall-Protection-Kits/8046/",
        "https://www.rshughes.com/c/Lanyards-Lifelines-Fall-Limiters/8061/",
        "https://www.rshughes.com/c/Fire-Blankets/8048/",
        "https://www.rshughes.com/c/Fire-Extinguishers/8432/",
        "https://www.rshughes.com/c/Fire-Extinguisher-Labels/7144/",
        "https://www.rshughes.com/c/Fire-Hazard-Labels/7073/",
        "https://www.rshughes.com/c/Firestop-Pass-Through-Devices-Parts/8050/",
        "https://www.rshughes.com/c/Firestop-Pipe-Collars-Cast-In-Devices-Accessories/8051/",
        "https://www.rshughes.com/c/Firestop-Sheets-Wraps-Pillows/8052/",
        "https://www.rshughes.com/c/Smoking-Receptacles/8439/",
        "https://www.rshughes.com/c/Anti-Fatigue-Floor-Mats-And-Ergonomic-Flooring-Kits/8025/",
        "https://www.rshughes.com/c/Carpeted-Entry-Mats/8029/",
        "https://www.rshughes.com/c/Cleanroom-Floor-Mats/8125/",
        "https://www.rshughes.com/c/Cleanroom-Mat-Frames/8126/",
        "https://www.rshughes.com/c/Flooring-Installation-Accessories/8055/",
        "https://www.rshughes.com/c/Non-Conductive-Switchboard-Matting/8072/",
        "https://www.rshughes.com/c/shipping:shipping-room-supplies:mats:anti-fatigue-mats/236/",
        "https://www.rshughes.com/c/shipping:shipping-room-supplies:mats:brush-mats/259/",
        "https://www.rshughes.com/c/shipping:shipping-room-supplies:mats:carpet-mats/266/",
        "https://www.rshughes.com/c/shipping:shipping-room-supplies:mats:diamond-plate-mats/299/",
        "https://www.rshughes.com/c/shipping:shipping-room-supplies:mats:drainage-mats/303/",
        "https://www.rshughes.com/c/shipping:shipping-room-supplies:mats:entry-mats/314/",
        "https://www.rshughes.com/c/shipping:shipping-room-supplies:mats:marble-mats/415/",
        "https://www.rshughes.com/c/Wet-Condition-Floor-Mats/8102/",
        "https://www.rshughes.com/c/Emergency-Showers-Eyewash-Stations/8155/",
        "https://www.rshughes.com/c/Eyewash-Shower-Station-Solutions-Parts/8153/",
        "https://www.rshughes.com/c/Bandages-Wound-Dressings/8114/",
        "https://www.rshughes.com/c/CPR-Emergency-Response-Equipment/8119/",
        "https://www.rshughes.com/c/First-Aid-Kits-Kit-Refills/8430/",
        "https://www.rshughes.com/c/Biohazard-Cleanup-Kits/8116/",
        "https://www.rshughes.com/c/Examination-Gowns-Drapes-And-Wraps/8156/",
        "https://www.rshughes.com/c/Swabs-Applicators-Examination-Brushes/8259/",
        "https://www.rshughes.com/c/Medicines-And-Health-Supplements/8215/",
        "https://www.rshughes.com/c/Key-Padlock-Cabinets-Stations-Storage/8186/",
        "https://www.rshughes.com/c/Lockout-Tagout-Device-Cabinets-Stations-Storage/8195/",
        "https://www.rshughes.com/c/Lockout-Tagout-Labels/7090/",
        "https://www.rshughes.com/c/Lockout-Tagout-Tags/7092/",
        "https://www.rshughes.com/c/Lockout-Tagout-Training-Materials/8200/",
        "https://www.rshughes.com/c/Cables-Cable-Lockout-Devices-Systems/8121/",
        "https://www.rshughes.com/c/Circuit-Breaker-Fuse-Lockout-Devices-Systems/8123/",
        "https://www.rshughes.com/c/Drum-Plug-Locking-Devices/8139/",
        "https://www.rshughes.com/c/Electrical-Plug-Switch-Lockout-Devices/8145/",
        "https://www.rshughes.com/c/Gas-Cylinder-Lockout-Devices/8167/",
        "https://www.rshughes.com/c/Group-Lockout-Boxes/8171/",
        "https://www.rshughes.com/c/Lockout-Tagout-Accessories/8192/",
        "https://www.rshughes.com/c/Lockout-Tagout-Hasps/8197/",
        "https://www.rshughes.com/c/Lockout-Tagout-Kits/8199/",
        "https://www.rshughes.com/c/Pneumatic-Lockout-Devices/8217/",
        "https://www.rshughes.com/c/Valve-Lockout-Devices/8262/",
        "https://www.rshughes.com/c/Lockout-Tagout-Equipment-Shutoff-Signs/9163/",
        "https://www.rshughes.com/c/Non-Adhesive-Tamper-Evident-Seals/8071/",
        "https://www.rshughes.com/c/Combination-Padlocks/8304/",
        "https://www.rshughes.com/c/Keyed-Safety-Padlocks/8189/",
        "https://www.rshughes.com/c/Padlock-Kits/8213/",
        "https://www.rshughes.com/c/Cleanroom-Gloves/8591/",
        "https://www.rshughes.com/c/Cleanroom-Smocks-Coveralls-Pants/8300/",
        "https://www.rshughes.com/c/Footwear-Accessories/8315/",
        "https://www.rshughes.com/c/Joint-Protection/8112/",
        "https://www.rshughes.com/c/Disposable-Gloves/8420/",
        "https://www.rshughes.com/c/General-Work-Gloves/8317/",
        "https://www.rshughes.com/c/High-Performance-Gloves/8293/",
        "https://www.rshughes.com/c/Mitts-Finger-Cots-Glove-Accessories/8163/",
        "https://www.rshughes.com/c/Earplugs-Protective-Earmuffs/8342/",
        "https://www.rshughes.com/c/Faceshields-Headgear-Accessories/8323/",
        "https://www.rshughes.com/c/Helmets-Hard-Hats/7146/",
        "https://www.rshughes.com/c/Protective-Eyewear-Accessories/8228/",
        "https://www.rshughes.com/c/Protective-Hats-Head-Coverings/8115/",
        "https://www.rshughes.com/c/Welding-Helmets-Accessories/8409/",
        "https://www.rshughes.com/c/Arc-Flash-Flame-Resistant-Personal-Protection/8347/",
        "https://www.rshughes.com/c/Chemical-Resistant-Protective-Gear/8287/",
        "https://www.rshughes.com/c/Cut-Resistant-Protective-Gear/8307/",
        "https://www.rshughes.com/c/Rainwear/8381/",
        "https://www.rshughes.com/c/Welding-Protective-Gear/8263/",
        "https://www.rshughes.com/c/Aprons-Accessories/8278/",
        "https://www.rshughes.com/c/Coats-Jackets-Vests/8301/",
        "https://www.rshughes.com/c/Coveralls/8030/",
        "https://www.rshughes.com/c/High-Visibility-Reflective-Workwear/8350/",
        "https://www.rshughes.com/c/Work-Smocks-Lab-Coats-Scrubs/8314/",
        "https://www.rshughes.com/c/Duffel-Bag-Accessories/8140/",
        "https://www.rshughes.com/c/Protective-Duffel-Bags/8226/",
        "https://www.rshughes.com/c/Disposable-Respirators-Dust-Masks/8133/",
        "https://www.rshughes.com/c/Surgical-Masks/8257/",
        "https://www.rshughes.com/c/Emergency-Escape-Respirators/8041/",
        "https://www.rshughes.com/c/Respirator-Bags-Cases-Dispensers/8087/",
        "https://www.rshughes.com/c/Respirator-Cleaning-Supplies/8088/",
        "https://www.rshughes.com/c/Respirator-Repair-Kits/8091/",
        "https://www.rshughes.com/c/Full-Facepiece-Eyepieces-Lenses-Parts/8331/",
        "https://www.rshughes.com/c/Half-Full-Facepiece-Adapters-Small-Parts/8336/",
        "https://www.rshughes.com/c/Half-Full-Facepiece-Filter-Retainers/8337/",
        "https://www.rshughes.com/c/Half-Full-Facepiece-Harnesses-Straps/8338/",
        "https://www.rshughes.com/c/Half-Full-Facepiece-Nose-Cups-Parts/8339/",
        "https://www.rshughes.com/c/Half-Full-Facepieces/8175/",
        "https://www.rshughes.com/c/PAPR-SAR-Adapters-Small-Parts/8364/",
        "https://www.rshughes.com/c/PAPR-SAR-Air-Filtration-Panels/8365/",
        "https://www.rshughes.com/c/PAPR-SAR-Air-Pumps-Blowers-Parts/8366/",
        "https://www.rshughes.com/c/PAPR-SAR-Assemblies/8367/",
        "https://www.rshughes.com/c/PAPR-SAR-Batteries-Chargers-Power-Cords/8368/",
        "https://www.rshughes.com/c/PAPR-SAR-Belts-Straps/8369/",
        "https://www.rshughes.com/c/PAPR-SAR-Breathing-Tubes-Air-Hoses-And-Fittings/8370/",
        "https://www.rshughes.com/c/Reusable-Respirator-Cartridges-Filters/8241/",
        "https://www.rshughes.com/c/Neck-Shrouds-Protectors/8362/",
        "https://www.rshughes.com/c/Reusable-Respirator-Headcovers-Helmets-Hoods/8388/",
        "https://www.rshughes.com/c/SCBA-Assemblies-And-Cylinders/8445/",
        "https://www.rshughes.com/c/Welding-Respirators/8101/",
        "https://www.rshughes.com/c/Air-Quality-Monitors-Detectors/8024/",
        "https://www.rshughes.com/c/Fixed-Systems/8503/",
        "https://www.rshughes.com/c/Fixed-Systems-Accessories/8504/",
        "https://www.rshughes.com/c/Calibration-Gas-Accessories/8508/",
        "https://www.rshughes.com/c/Docks-Cradles-Power-Accessories/8510/",
        "https://www.rshughes.com/c/Probes-Pumps/8511/",
        "https://www.rshughes.com/c/Replacement-Sensors/8509/",
        "https://www.rshughes.com/c/Service-Plans-Subscriptions/8512/",
        "https://www.rshughes.com/c/Spare-Parts/8513/",
        "https://www.rshughes.com/c/Portable-Gas-Monitors/8505/",
        "https://www.rshughes.com/c/Environmental-Surface-Sampling-Kits/8044/",
        "https://www.rshughes.com/c/Inspection-Asset-Management-Equipment/8507/",
        "https://www.rshughes.com/c/Respirator-Fit-Testing-Kits-Accessories/8089/",
        "https://www.rshughes.com/c/Radiation-Environment-Testing/8515/",
        "https://www.rshughes.com/c/Testing-Equipment-Accessories/8516/",
        "https://www.rshughes.com/c/MSDS-GHS-Data-Sheet-Binders-Accessories/8202/",
        "https://www.rshughes.com/c/OSHA-Label-Stations/8209/",
        "https://www.rshughes.com/c/OSHA-Tag-Stations/8210/",
        "https://www.rshughes.com/c/Emergency-Response-Training-Materials/8147/",
        "https://www.rshughes.com/c/Fall-Protection-Training-Materials/8161/",
        "https://www.rshughes.com/c/GHS-Hazardous-Communication-Safety-Training-Materials/8166/",
        "https://www.rshughes.com/c/Injury-Prevention-Training-Materials/8184/",
        "https://www.rshughes.com/c/Lockout-Tagout-Training-Materials/8200/",
        "https://www.rshughes.com/c/OSHA-Compliance-Training-Materials/8208/",
        "https://www.rshughes.com/c/Work-Permits/8103/",
        "https://www.rshughes.com/c/Absorbent-Storage-Cabinet-Cart-Accessories/8108/",
        "https://www.rshughes.com/c/Absorbent-Storage-Cabinets-Carts/8109/",
        "https://www.rshughes.com/c/Absorbent-Mats-Rolls-Rugs/8104/",
        "https://www.rshughes.com/c/Absorbent-Pads/8105/",
        "https://www.rshughes.com/c/Absorbent-Pillows/8106/",
        "https://www.rshughes.com/c/Absorbent-Socks-Booms/8107/",
        "https://www.rshughes.com/c/Absorbent-Sweeps-Nets/8110/",
        "https://www.rshughes.com/c/Granular-Absorbents/8170/",
        "https://www.rshughes.com/c/Laboratory-Bench-Liners/8060/",
        "https://www.rshughes.com/c/Hazardous-Material-Storage-Cabinet-Accessories/8178/",
        "https://www.rshughes.com/c/Hazardous-Material-Storage-Cabinets/8181/",
        "https://www.rshughes.com/c/Drum-Safety-Can-Covers-Grates-Screens/8136/",
        "https://www.rshughes.com/c/Drum-Carts-Lifters-Handling-Accessories/8137/",
        "https://www.rshughes.com/c/Drum-Grounding-Wires/8138/",
        "https://www.rshughes.com/c/Faucets-Funnels-Accessories/8162/",
        "https://www.rshughes.com/c/Safety-Cans/8245/",
        "https://www.rshughes.com/c/Spill-Containment-Drums/8254/",
        "https://www.rshughes.com/c/Drain-Covers-Guards-Plugs/8135/",
        "https://www.rshughes.com/c/Portable-Berms-Berm-Kits/8218/",
        "https://www.rshughes.com/c/Spill-Leak-Repair-Accessories/8251/",
        "https://www.rshughes.com/c/Spill-Containment-Booms/8252/",
        "https://www.rshughes.com/c/Spill-Containment-Drums/8254/",
        "https://www.rshughes.com/c/Spill-Deck-Pallet-Workstation-Accessories/8394/",
        "https://www.rshughes.com/c/Spill-Decks-Pallets/8395/",
        "https://www.rshughes.com/c/Spill-Workstations/8396/",
        "https://www.rshughes.com/c/Spill-Response-Kits-Refills/8256/",
        "https://www.rshughes.com/c/Trays-Drip-Pans/8260/",
        // "https://www.rshughes.com/c/shipping:corrugated-boxes:bulk-cargo-containers/36/",
        // "https://www.rshughes.com/c/shipping:corrugated-mailers/5/",
        // "https://www.rshughes.com/c/shipping:corrugated-boxes:file-storage-boxes:storage:drawer-steel-plus-boxes/498/",
        // "https://www.rshughes.com/c/shipping:corrugated-boxes:file-storage-boxes:auto-lock-file-storage-boxes/246/",
        // "https://www.rshughes.com/c/shipping:corrugated-boxes:hazardous-materials-boxes-supplies:haz-mat-paint-can-foam-shipping-kits/360/",
        // "https://www.rshughes.com/c/shipping:corrugated-boxes:hazardous-materials-paint-can-shipping-boxes/672/",
        // "https://www.rshughes.com/c/shipping:corrugated-boxes:hazardous-material-paint-cans-and-plastic-jugss/675/",
        // "https://www.rshughes.com/c/shipping:corrugated-boxes:heavy-duty-boxes/80/",
        // "https://www.rshughes.com/c/shipping:corrugated-boxes:korrvu-packaging/94/",
        // "https://www.rshughes.com/c/shipping:corrugated-mailers:corrugated-carrying-cases/49/",
        // "https://www.rshughes.com/c/shipping:corrugated-boxes:moving-boxes/113/",
        // "https://www.rshughes.com/c/shipping:corrugated-boxes:multi-depth-boxes/114/",
        // "https://www.rshughes.com/c/shipping:chipboard-cartons:apparel-boxes/20/",
        // "https://www.rshughes.com/c/shipping:chipboard-cartons:gift-boxes:kraft-gift-boxes/401/",
        // "https://www.rshughes.com/c/shipping:chipboard-cartons:deluxe-gift-boxes:deluxe-gift-box-bottoms/295/",
        // "https://www.rshughes.com/c/shipping:chipboard-cartons:jewelry-boxes/91/",
        // "https://www.rshughes.com/c/shipping:chipboard-cartons:reverse-tuck-folding-cartons/144/",
        // "https://www.rshughes.com/c/shipping:chipboard-cartons:stationery-folding-cartons/159/",
        // "https://www.rshughes.com/c/shipping:chipboard-cartons:stationery-setup-cartons/160/",
        // "https://www.rshughes.com/c/shipping:corrugated-boxes:corrugated-sheets-pads:anti-slip-pallet-paper/237/",
        // "https://www.rshughes.com/c/shipping:corrugated-boxes:corrugated-sheets-pads:chipboard-pads/270/",
        // "https://www.rshughes.com/c/shipping:corrugated-boxes:corrugated-sheets-pads:corrugated-layer-pads/289/",
        // "https://www.rshughes.com/c/shipping:corrugated-boxes:corrugated-sheets-pads:corrugated-sheets/290/",
        // "https://www.rshughes.com/c/shipping:corrugated-boxes:corrugated-sheets-pads:honeycomb-sheets/368/",
        // "https://www.rshughes.com/c/shipping:corrugated-boxes:corrugated-sheets-pads:plastic-sheets/444/",
        // "https://www.rshughes.com/c/shipping:corrugated-boxes:corrugated-sheets-pads:plastic-sheets/444/",
        // "https://www.rshughes.com/c/shipping:corrugated-boxes:general-corrugated-boxes/540/",
        // "https://www.rshughes.com/c/shipping:packing-fill:bubble-rolls:adhesive-bubble-rolls/229/",
        // "https://www.rshughes.com/c/shipping:packing-fill:bubble-rolls:air-bubble-rolls/233/",
        // "https://www.rshughes.com/c/shipping:packing-fill:bubble-rolls:anti-static-air-bubble-rolls/241/",
        // "https://www.rshughes.com/c/shipping:packing-fill:bubble-pouches/34/",
        // "https://www.rshughes.com/c/shipping:packing-fill:bubble-rolls:cohesive-bubble-rolls/281/",
        // "https://www.rshughes.com/c/shipping:packing-fill:bubble-rolls:upsable-bubble-rolls/512/",
        // "https://www.rshughes.com/c/shipping:packing-fill:cushion-systems:fill-air-rf-bags/324/",
        // "https://www.rshughes.com/c/shipping:packing-fill:cushion-systems:instapak-quick-foam-bags/381/",
        // "https://www.rshughes.com/c/shipping:packing-fill:cushion-systems:mini-pak-r-air-cushion-machine/425/",
        // "https://www.rshughes.com/c/shipping:packing-fill:foam-rolls:air-foam-rolls/235/",
        // "https://www.rshughes.com/c/shipping:packing-fill:foam-rolls:anti-static-foam-rolls/243/",
        // "https://www.rshughes.com/c/shipping:packing-fill:foam-rolls:cohesive-foam-rolls/282/",
        // "https://www.rshughes.com/c/shipping:packing-fill:foam-corners-edge-protectors/67/",
        // "https://www.rshughes.com/c/shipping:packing-fill:foam-rolls:foam-pouches/340/",
        // "https://www.rshughes.com/c/shipping:packing-fill:foam-rolls:foam-sheets/341/",
        // "https://www.rshughes.com/c/shipping:packing-fill:foam-rolls:upsable-foam-rolls/513/",
        // "https://www.rshughes.com/c/shipping:packing-fill:loose-fill:biodegradable-loose-fill/250/",
        // "https://www.rshughes.com/c/shipping:packing-fill:dispensers:flo-vac-ceiling-mount-vacuum-dispensers/335/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:impulse-sealers-kits/85/",
        // "https://www.rshughes.com/c/shipping:mailing-tubes:adjustable-tubes/18/",
        // "https://www.rshughes.com/c/shipping:mailing-tubes:square-mailing-tubes/154/",
        // "https://www.rshughes.com/c/shipping:mailing-tubes:triangle-mailing-tubes/168/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:paper-office-envelopes/125/",
        // "https://www.rshughes.com/c/shipping:packing-list-envelopes/9/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:paper-bags/124/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:bubble-mailers:glamour-bubble-mailers/348/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:flat-mailers/65/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:jet-lite-nylon-reinforced-mailers/90/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:padded-mailers/121/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:poly-mailers-envelopes:bubble-lined-poly-mailers/260/",
        // "https://www.rshughes.com/c/shipping:paper-rolls:indented-kraft-paper-rolls/86/",
        // "https://www.rshughes.com/c/shipping:paper-rolls:kraft-paper-rolls/98/",
        // "https://www.rshughes.com/c/shipping:paper-rolls:paper-sheets:poly-coated-kraft-paper-sheets/449/",
        // "https://www.rshughes.com/c/shipping:paper-rolls:newsprint-rolls/116/",
        // "https://www.rshughes.com/c/shipping:paper-rolls:versa-pak-master-rolls/175/",
        // "https://www.rshughes.com/c/shipping:paper-rolls:wrapping-tissue:crinkle-paper/292/",
        // "https://www.rshughes.com/c/shipping:paper-rolls:wrapping-tissue:economy-wrapping-tissue/313/",
        // "https://www.rshughes.com/c/shipping:paper-rolls:roll-cutters/146/",
        // "https://www.rshughes.com/c/shipping:paper-rolls:bogus-kraft-paper-rolls/28/",
        // "https://www.rshughes.com/c/shipping:paper-rolls:butcher-paper-rolls/38/",
        // "https://www.rshughes.com/c/shipping:paper-rolls:freezer-paper-rolls/69/",
        // "https://www.rshughes.com/c/Tyvek-Rolls/583/",
        // "https://www.rshughes.com/c/shipping:paper-rolls:paper-sheets:waxed-paper-sheets/520/",
        // "https://www.rshughes.com/c/shipping:paper-rolls:VCI-paper-rolls/173/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:furniture-covers-mattress-bags:furniture-covers/345/",
        // "https://www.rshughes.com/c/Garment-Bags/590/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:furniture-covers-mattress-bags:mattress-bags/417/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:mini-grip-reclosable-poly-bags:mini-grip-anti-static-reclosable-poly-bags/420/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:mini-grip-reclosable-poly-bags:minigrip-reclosable-lab-guard-uv-protection-bags/422/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:mini-grip-reclosable-poly-bags:minigrip-reclosable-greenline-biodegradable-bags/421/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:mini-grip-reclosable-poly-bags:2-mil-mini-grip-reclosable-poly-bags/194/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:mini-grip-reclosable-poly-bags:mini-grip-slider-grip-reclosable-poly-bags/423/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:flat-poly-bags:1-mil-flat-poly-bags/187/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:polypropylene-poly-bags:flat-polypropylene-poly-bags/328/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:gusseted-poly-bags/75/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:polypropylene-poly-bags:gusseted-polypropylene-poly-bags/355/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:twist-ties/170/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:poly-sheeting:black-poly-sheeting/278/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:poly-sheeting:clear-poly-sheeting/252/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:anti-static-poly-tubing/19/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:auto-fill-poly-bags/22/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:black-poly-tubing:4-mil-black-poly-tubing/209/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:poly-tubing:1.5-mil-poly-tubing/184/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:poly-tubing:poly-tubing-dispensers/454/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:reclosable-poly-bags:double-track-reclosable-poly-bags/301/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:gusseted-reclosable-poly-bag/76/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:reclosable-poly-bags:2-mil-reclosable-poly-bags/197/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:reclosable-poly-bags:2-mil-reclosable-poly-bags-w:-hang-hole/198/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:polypropylene-poly-bags:reclosable-polypropylene-poly-bags/462/",
        // "https://www.rshughes.com/c/Resealable-Poly-Bags/592/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:reclosable-poly-bags:slide-seal-reclosable-poly-bags/494/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:white-block-reclosable-poly-bags/177/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:static-shielding-bags:dri-shield-moisture-barrier-bags/304/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:top-sheeting:economy-top-sheeting/312/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:top-sheeting:goodwrappers-top-sheeting/350/",
        // "https://www.rshughes.com/c/shipping:shipping-room-supplies:carton-sizer:reducer/41/",
        // "https://www.rshughes.com/c/shipping:shipping-room-supplies:shipping-indicators:drop-n-tell/305/",
        // "https://www.rshughes.com/c/shipping:shipping-room-supplies:shipping-indicators:humidity-indicators/370/",
        // "https://www.rshughes.com/c/shipping:shipping-room-supplies:shipping-indicators:shockwatch/486/",
        // "https://www.rshughes.com/c/shipping:shipping-room-supplies:shipping-indicators:tiltwatch/506/",
        // "https://www.rshughes.com/c/shipping:shipping-room-supplies:shipping-indicators:tip-n-tell/508/",
        // "https://www.rshughes.com/c/shipping:shipping-room-supplies:desiccants/58/",
        // "https://www.rshughes.com/c/Magnetic-Accessories/597/",
        // "https://www.rshughes.com/c/shipping:shipping-room-supplies:markers:marsh-88-valve-markers/416/",
        // "https://www.rshughes.com/c/shipping:shipping-room-supplies:markers:mean-streak-markers/418/",
        // "https://www.rshughes.com/c/shipping:shipping-room-supplies:markers:sharpie-accent-highlighters/483/",
        // "https://www.rshughes.com/c/shipping:shipping-room-supplies:markers:sharpie-markers/484/",
        // "https://www.rshughes.com/c/shipping:shipping-room-supplies:markers:sharpie-pallet-markers/485/",
        // "https://www.rshughes.com/c/shipping:corrugated-boxes:pallets/123/",
        // "https://www.rshughes.com/c/shipping:mailing-bags-envelopes:pallet-covers-bin-liners/122/",
        // "https://www.rshughes.com/c/shipping:shipping-room-supplies:plastic-pallets/130/",
        // "https://www.rshughes.com/c/shipping:corrugated-boxes:honeycomb-pallet-runners:wood-pallets/538/",
        // "https://www.rshughes.com/c/Rubber-Bands/585/",
        // "https://www.rshughes.com/c/Staples-Staplers/584/",
        // "https://www.rshughes.com/c/White-Boards-Cork-Boards-Accessories/586/",
        // "https://www.rshughes.com/c/shipping:shrink-film:ipg-polyolefin-shrink-film/89/",
        // "https://www.rshughes.com/c/shipping:strapping-edge-protectors:cable-ties:beaded-security-ties/249/",
        // "https://www.rshughes.com/c/shipping:strapping-edge-protectors:cable-ties:black-uv-cable-ties/254/",
        // "https://www.rshughes.com/c/Cable-Tie-Guns/5064/",
        // "https://www.rshughes.com/c/Cable-Tie-Mounts/599/",
        // "https://www.rshughes.com/c/shipping:strapping-edge-protectors:cable-ties:colored-cable-ties/284/",
        // "https://www.rshughes.com/c/shipping:strapping-edge-protectors:cable-ties:heavy-duty-natural-cable-ties/364/",
        // "https://www.rshughes.com/c/shipping:strapping-edge-protectors:cable-ties:identification-cable-ties/373/",
        // "https://www.rshughes.com/c/shipping:strapping-edge-protectors:cable-ties:natural-cable-ties/430/",
        // "https://www.rshughes.com/c/shipping:strapping-edge-protectors:cable-ties:resealable-cable-ties/471/",
        // "https://www.rshughes.com/c/shipping:strapping-edge-protectors:hand-grade-polypropylene-strapping:8-x-8-core-hand-grade-signode-comparable-poly-strapping/225/",
        // "https://www.rshughes.com/c/shipping:strapping-edge-protectors:polyester-strapping:poly-cord-strapping/450/",
        // "https://www.rshughes.com/c/shipping:strapping-edge-protectors:poly-strapping-tools-buckles-seals:poly-strapping-buckles/452/",
        // "https://www.rshughes.com/c/shipping:strapping-edge-protectors:polyester-strapping:poly-strapping-kits/453/",
        // "https://www.rshughes.com/c/shipping:strapping-edge-protectors:steel-strapping/161/",
        // "https://www.rshughes.com/c/shipping:strapping-edge-protectors:edge-protectors:plain-edge-protectors/443/",
        // "https://www.rshughes.com/c/shipping:strapping-edge-protectors:edge-protectors:strapping-guards/499/",
        // "https://www.rshughes.com/c/shipping:strapping-edge-protectors:tying-twine/171/",
        // "https://www.rshughes.com/c/shipping:stretch-film:bundling-stretch-film/37/",
        // "https://www.rshughes.com/c/shipping:stretch-film:hand-stretch-film/78/",
        // "https://www.rshughes.com/c/shipping:stretch-film:machine-stretch-film/102/",
        // "https://www.rshughes.com/c/shipping:stretch-film:dispensers/60/",
        // "https://www.rshughes.com/c/Case-Sealers/3069/",
        // "https://www.rshughes.com/c/Dry-Erase-Signs-Communication-Boards/9088/",
        // "https://www.rshughes.com/c/Floor-Stand-Signs/9114/",
        // "https://www.rshughes.com/c/Homeland-Security-Alert-Signs/9115/",
        // "https://www.rshughes.com/c/Marine-International-Maritime-Organization-IMO-Signs/9118/",
        // "https://www.rshughes.com/c/Access-Security-Signs/9123/",
        // "https://www.rshughes.com/c/Accident-Emergency-Response-Signs/9124/",
        // "https://www.rshughes.com/c/Employee-Information-Regulatory-Signs/9125/",
        // "https://www.rshughes.com/c/Exit-Entrance-Signs/9126/",
        // "https://www.rshughes.com/c/Food-Water-Sanitation-Signs/9160/",
        // "https://www.rshughes.com/c/Personal-Hygiene-Restroom-Signs/9166/",
        // "https://www.rshughes.com/c/Hospital-Department-Location-Signs/9129/",
        // "https://www.rshughes.com/c/Maintenance-Repair-Signs/9133/",
        // "https://www.rshughes.com/c/Material-Handling-Shipping-Receiving-Signs/9134/",
        // "https://www.rshughes.com/c/Motivational-Humorous-Signs/9135/",
        // "https://www.rshughes.com/c/Pet-Restriction-Information-Signs/9167/",
        // "https://www.rshughes.com/c/Restricted-Activities-Signs/9169/",
        // "https://www.rshughes.com/c/Phone-Location-Signs/9138/",
        // "https://www.rshughes.com/c/Recycling-Conservation-Green-Signs/9141/",
        // "https://www.rshughes.com/c/Red-Tag-5S-Equipment-Handling-Process-Signs-Stations-Boards/9142/",
        // "https://www.rshughes.com/c/Remodeling-Construction-Notice-Signs/9143/",
        // "https://www.rshughes.com/c/California-Proposition-65-Signs/9140/",
        // "https://www.rshughes.com/c/Fall-Prevention-And-Floor-Obstacle-Hazard-Signs/9157/",
        // "https://www.rshughes.com/c/Fire-Safety-Signs/9127/",
        // "https://www.rshughes.com/c/Severe-Weather-Disaster-Shelter-Signs/9147/",
        // "https://www.rshughes.com/c/First-Aid-Eyewash-Shower-Breathing-Apparatus-Signs/9159/",
        // "https://www.rshughes.com/c/Hazardous-Material-MSDS-SOP-RTK-Spill-Response-Signs/9162/",
        // "https://www.rshughes.com/c/Lockout-Tagout-Equipment-Shutoff-Signs/9163/",
        // "https://www.rshughes.com/c/Radiation-Laser-Signs/9168/",
        // "https://www.rshughes.com/c/Safety-Awareness-PPE-Signs/9170/",
        // "https://www.rshughes.com/c/Parking-Signs/9137/",
        // "https://www.rshughes.com/c/Color-Cards/9155/",
        // "https://www.rshughes.com/c/Graphic-Film-Plastic-Applicators/9161/",
        // "https://www.rshughes.com/c/Low-Friction-Sleeves/9164/",
        // "https://www.rshughes.com/c/Signmaking-Film/9174/",
        // "https://www.rshughes.com/c/MSDS-Compliance-SOP-And-RTK-Information-Centers/9132/",
        // "https://www.rshughes.com/c/Placard-Holders/9139/",
        // "https://www.rshughes.com/c/Roll-Up-Flags-Flag-Assemblies/9144/",
        // "https://www.rshughes.com/c/Sign-Clips-Hangers-Hooks/9148/",
        // "https://www.rshughes.com/c/Sign-Floor-Stands/9149/",
        // "https://www.rshughes.com/c/Sign-Mounting-Adapters-Brackets-Sets/9171/",
        // "https://www.rshughes.com/c/Sign-Mounting-Posts-Bases/9172/",
        // "https://www.rshughes.com/c/Sign-Mounting-Strips-Straps/9173/",
        // "https://www.rshughes.com/c/Sign-Panels/9151/",
        // "https://www.rshughes.com/c/Sign-Tools-Cleaners/9152/",
        // "https://www.rshughes.com/c/Sign-Blanks-Preprinted-Headers/9122/",
        // "https://www.rshughes.com/c/Fire-Safety-Signs/9127/",
        // "https://www.rshughes.com/c/Severe-Weather-Disaster-Shelter-Signs/9147/",

        // Tapes
        /*"https://www.rshughes.com/c/Aerospace-Tapes/3003/",
        "https://www.rshughes.com/c/Automotive-Tapes/3005/",
        "https://www.rshughes.com/c/Bonding-Tapes/3031/",
        "https://www.rshughes.com/c/Foam-Mounting-Tapes/3046/",
        "https://www.rshughes.com/c/Transfer-Tapes/3062/",
        "https://www.rshughes.com/c/VHB-Tapes/3063/",
        "https://www.rshughes.com/c/Cloth-Tapes/3033/",
        "https://www.rshughes.com/c/Duct-Tapes/3041/",
        "https://www.rshughes.com/c/Gaffers-Tapes/3047/",
        "https://www.rshughes.com/c/Conductive-Tapes/3035/",
        "https://www.rshughes.com/c/Copper-Tapes/3037/",
        "https://www.rshughes.com/c/Electrical-Marking-Tapes/3044/",
        "https://www.rshughes.com/c/Insulating-Tapes/3050/",
        "https://www.rshughes.com/c/Static-Control-Tapes/3060/",
        "https://www.rshughes.com/c/Water-Contact-Indicator-Tapes/3066/",
        "https://www.rshughes.com/c/Flashing-Sealing-Tapes/3010/",
        "https://www.rshughes.com/c/Flexographic-Plate-Mounting-Tapes/3011/",
        "https://www.rshughes.com/c/Single-Sided-Foam-Tapes/3057/",
        "https://www.rshughes.com/c/Single-Sided-Foam-Tapes/3057/",
        "https://www.rshughes.com/c/Copper-Tapes/3037/",
        "https://www.rshughes.com/c/Lead-Tapes/3051/",
        "https://www.rshughes.com/c/Anti-Slip-Tapes/3030/",
        "https://www.rshughes.com/c/Grip-Tapes/3048/",
        "https://www.rshughes.com/c/Electrical-Marking-Tapes/3044/",
        "https://www.rshughes.com/c/Marking-Tapes/3052/",
        "https://www.rshughes.com/c/Reflective-Tapes/3056/",
        "https://www.rshughes.com/c/Warning-Tapes/3064/",
        "https://www.rshughes.com/c/Masking-Paper-Cloth-Film/3054/",
        "https://www.rshughes.com/c/Masking-Tapes/3053/",
        "https://www.rshughes.com/c/Painters-Tapes/3070/",
        "https://www.rshughes.com/c/Office-Tapes/3018/",
        "https://www.rshughes.com/c/Standard-Box-Sealing-Tapes/3021/",
        "https://www.rshughes.com/c/Filament-Strapping-Tapes/3020/",
        "https://www.rshughes.com/c/Water-Activated-Tapes/3075/",
        "https://www.rshughes.com/c/Label-Protection-Tapes/7035/",
        "https://www.rshughes.com/c/Package-Repair-Sheets-And-Carry-Handles/3076/",
        "https://www.rshughes.com/c/shipping:packing-tape:bag-tape/631/",
        "https://www.rshughes.com/c/Pipe-Banding-Tapes/7016/",
        "https://www.rshughes.com/c/Reclosable-Fasteners/3015/",
        "https://www.rshughes.com/c/Slick-Surface-Tapes/3022/",
        "https://www.rshughes.com/c/Specialty-Application-Tapes/3023/",
        "https://www.rshughes.com/c/Splicing-Core-Starting-Tapes/3024/",
        "https://www.rshughes.com/c/Bumpers-Spacers/3032/",
        "https://www.rshughes.com/c/Floor-Mats-Mat-Frames/3045/",
        "https://www.rshughes.com/c/Surface-Protective-Films-Tapes/3061/",
        "https://www.rshughes.com/c/Dispensers-Applicators-Accessories-Tools/3039/",
        "https://www.rshughes.com/c/Tape-Primers/3027/",
        "https://www.rshughes.com/c/Thread-Sealant-Tapes/3028/",
        "https://www.rshughes.com/c/Case-Sealers/3069/",*/
        // "https://www.rshughes.com/c/Bench-Grinders/10067/",
        // "https://www.rshughes.com/c/Planers-Biscuit-Joiners-Routers/10066/",
        // "https://www.rshughes.com/c/Power-Tool-Adapters/1205500/",
        // "https://www.rshughes.com/c/Collets-And-Collet-Inserts/1205304/",
        // "https://www.rshughes.com/c/Contact-Arms/1200804/",
        // "https://www.rshughes.com/c/Contact-Wheels/1200604/",
        // "https://www.rshughes.com/c/Drill-Chucks/1212604/",
        // "https://www.rshughes.com/c/Dust-Collection-Systems/1207304/",
        // "https://www.rshughes.com/c/Dynamitt-Accessories/1216404/",
        // "https://www.rshughes.com/c/Leveling-Jacks/1218400/",
        // "https://www.rshughes.com/c/Platen-Pads/1201604/",
        // "https://www.rshughes.com/c/Tool-Handles-Collars/1217404/",
        // "https://www.rshughes.com/c/Electrical-Accessories-And-Parts/1201110/",
        // "https://www.rshughes.com/c/Tune-Up-And-Repair-Tools-Kits/1201100/",
        // "https://www.rshughes.com/c/Wet-Tool-Accessories/1215200/",
        // "https://www.rshughes.com/c/Accessories-For-Wheel-Maintenance/1202204/",
        // "https://www.rshughes.com/c/Accessory-Wrenches/1246100/",
        // "https://www.rshughes.com/c/Bit-Holders/5203/",
        // "https://www.rshughes.com/c/Drilling-Cutting-Sawing-Accessories/10053/",
        // "https://www.rshughes.com/c/Driver-Bits/5202/",
        // "https://www.rshughes.com/c/Faceplates-Hubs-Adapters-Retainer-Nuts/718/",
        // "https://www.rshughes.com/c/File-Belt-Sander-Accessories/697/",
        // "https://www.rshughes.com/c/Descaling-Tools/1204300/",
        // "https://www.rshughes.com/c/buffing-polishing-finishing-tools/719/",
        // "https://www.rshughes.com/c/cut-off-tools/683/",
        // "https://www.rshughes.com/c/die-grinders/684/",
        // "https://www.rshughes.com/c/sanding-power-tools/720/",
        // "https://www.rshughes.com/c/Air-Tools-Accessories/1246404/",
        // "https://www.rshughes.com/c/Air-Compressors/10054/",
        // "https://www.rshughes.com/c/Downdraft-Sanding-Tables/1218704/",
        // "https://www.rshughes.com/c/Safety-Air-Blow-Guns/10122/",
        // "https://www.rshughes.com/c/Power-Drills/1211604/",
        // "https://www.rshughes.com/c/Electric-Screwdrivers/5094/",
        // "https://www.rshughes.com/c/Hammer-Drills-Jack-Hammers/10048/",
        // "https://www.rshughes.com/c/Grease-Guns/10058/",
        // "https://www.rshughes.com/c/Impact-Wrenches/10056/",
        // "https://www.rshughes.com/c/Nail-Guns-Staple-Guns/10051/",
        // "https://www.rshughes.com/c/Outdoor-Power-Equipment/10049/",
        // "https://www.rshughes.com/c/Pipe-Tools/10060/",
        // "https://www.rshughes.com/c/Radios-Speakers/10059/",
        // "https://www.rshughes.com/c/Saw-Blades/1235600/",
        // "https://www.rshughes.com/c/Power-Saws/10043/",
        // "https://www.rshughes.com/c/Adapters-Extensions/5204/",
        // "https://www.rshughes.com/c/Adjustable-Wrenches/5010/",
        // "https://www.rshughes.com/c/Axes-Hatchets/5221/",
        // "https://www.rshughes.com/c/Crowbars-Pry-Bars/5220/",
        // "https://www.rshughes.com/c/Electrical-Switch-Sticks/8039/",
        // "https://www.rshughes.com/c/Feeler-Gauge/5212/",
        // "https://www.rshughes.com/c/File-Tools-Sets/5218/",
        // "https://www.rshughes.com/c/Flag-Drivers/5208/",
        // "https://www.rshughes.com/c/Hammers-And-Mallets/5210/",
        // "https://www.rshughes.com/c/Hand-Deburring-Tools/5209/",
        // "https://www.rshughes.com/c/Hand-Saws-Hack-Saws/5219/",
        // "https://www.rshughes.com/c/Hand-Saws-Hack-Saws/5219/",
        // "https://www.rshughes.com/c/Hemostats/5032/",
        // "https://www.rshughes.com/c/Knife-Scalpel-Sets-Parts-Accessories/5107/",
        // "https://www.rshughes.com/c/Knives-Scalpels/5108/",
        // "https://www.rshughes.com/c/L-Keys/5207/",
        // "https://www.rshughes.com/c/Magnetic-Pickup-Tools/5217/",
        // "https://www.rshughes.com/c/Maintenance-Kits/5215/",
        // "https://www.rshughes.com/c/Mirrors-Magnifiers/5035/",
        // "https://www.rshughes.com/c/Pliers/5036/",
        // "https://www.rshughes.com/c/Probes-Pin-Vises-Scribes/5037/",
        // "https://www.rshughes.com/c/Scissors/5118/",
        // "https://www.rshughes.com/c/Screwdrivers-Nut-Drivers/5039/",
        // "https://www.rshughes.com/c/T-Handles/5206/",
        // "https://www.rshughes.com/c/Tape-Measures-And-Measuring-Tapes/5211/",
        // "https://www.rshughes.com/c/Tool-Wrap/5213/",
        // "https://www.rshughes.com/c/Tweezer-Replacement-Tips/5132/",
        // "https://www.rshughes.com/c/Tweezers/5133/",
        // "https://www.rshughes.com/c/Clamps-Vise-Grips/12006/",
        // "https://www.rshughes.com/c/Fasteners/12005/",
        // "https://www.rshughes.com/c/Hose-Clamps-Benders/12002/",
        // "https://www.rshughes.com/c/Machine-Keystock/12001/",
        // "https://www.rshughes.com/c/Metal-Bar-Stock/12003/",
        // "https://www.rshughes.com/c/Music-Wire-Stainless-Steel-Wire/5214/",
        // "https://www.rshughes.com/c/Auger-Bits/10047/",
        // "https://www.rshughes.com/c/Burrs/10002/",
        // "https://www.rshughes.com/c/Counterbores/10013/",
        // "https://www.rshughes.com/c/Countersinks/10014/",
        // "https://www.rshughes.com/c/Dies/10031/",
        // "https://www.rshughes.com/c/Annular-Cutters-Drill-Bits/10046/",
        // "https://www.rshughes.com/c/Drill-Bit-Blanks/10040/",
        // "https://www.rshughes.com/c/Extension-Drill-Bits/10038/",
        // "https://www.rshughes.com/c/Jobber-Length-Drill-Bits/10036/",
        // "https://www.rshughes.com/c/Mechanics-Length-Drill-Bits/10075/",
        // "https://www.rshughes.com/c/Reduced-Shank-Drill-Bits-S-D-Drill-Bits/10022/",
        // "https://www.rshughes.com/c/Screw-Machine-Length-Drill-Bits/10020/",
        // "https://www.rshughes.com/c/Spade-Drill-Bits/10039/",
        // "https://www.rshughes.com/c/Spotting-Drill-Bits/10037/",
        // "https://www.rshughes.com/c/Taper-Length-Drill-Bits/10021/",
        // "https://www.rshughes.com/c/End-Mills/10019/",
        // "https://www.rshughes.com/c/Indexable-Cutting-Tools-Accessories/10074/",
        // "https://www.rshughes.com/c/Indexable-Drill-Bits/10072/",
        // "https://www.rshughes.com/c/Indexable-End-Mills/10071/",
        // "https://www.rshughes.com/c/Indexable-Threading-Tools/10073/",
        // "https://www.rshughes.com/c/Indexable-Turning-Tools/10070/",
        // "https://www.rshughes.com/c/Punching-Tools/10045/",
        // "https://www.rshughes.com/c/Reamers/10012/",
        // "https://www.rshughes.com/c/Rotary-Hammer-Chisel-Drill-Bits/10052/",
        // "https://www.rshughes.com/c/Router-Bits/10042/",
        // "https://www.rshughes.com/c/Screw-Bolt-Extractors/10062/",
        // "https://www.rshughes.com/c/Step-Drill-Bits/10057/",
        // "https://www.rshughes.com/c/Taps/10033/",
        // "https://www.rshughes.com/c/Measuring-Tools/10005/",
        // "https://www.rshughes.com/c/Tool-Cabinets-Storage/10050/",
    ]
}

export default categories

//Chemicals-Lubricants